branch-defaults:
  master:
    environment: job-webapp-production
global:
  application_name: job_webapp
  branch: null
  default_ec2_keyname: job-webapp
  default_platform: PHP 7.3
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: job-webapp
  repository: null
  sc: git
  workspace_type: Application
